import { HuntCardProps } from '@/components/hunt-card'
import { OutfitterCardProps } from '@/components/outfitter-card'

export const mockHunts: HuntCardProps[] = [
  {
    id: 'trophy-whitetail-missouri',
    title: 'Trophy Whitetail Deer Hunt',
    outfitterName: 'Heartland Trophy Outfitters',
    species: 'Whitetail Deer',
    state: 'Missouri',
    pricePerPerson: 1800,
    rating: 4.9,
    reviewCount: 47,
    weaponTypes: ['Rifle', 'Bow'],
    lodgingIncluded: true,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'premium-elk-colorado',
    title: 'Premium Rocky Mountain Elk Hunt',
    outfitterName: 'Rockies Wilderness Outfitters',
    species: 'Elk',
    state: 'Colorado',
    pricePerPerson: 4500,
    rating: 4.8,
    reviewCount: 62,
    weaponTypes: ['Rifle', 'Bow', 'Muzzleloader'],
    lodgingIncluded: true,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'mule-deer-wyoming',
    title: 'Mule Deer Wilderness Hunt',
    outfitterName: 'Wind River Outfitters',
    species: 'Mule Deer',
    state: 'Wyoming',
    pricePerPerson: 3200,
    rating: 4.7,
    reviewCount: 38,
    weaponTypes: ['Rifle'],
    lodgingIncluded: false,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'black-bear-montana',
    title: 'Black Bear Spring Hunt',
    outfitterName: 'Big Sky Hunting Adventures',
    species: 'Black Bear',
    state: 'Montana',
    pricePerPerson: 2400,
    rating: 4.6,
    reviewCount: 29,
    weaponTypes: ['Bow', 'Rifle'],
    lodgingIncluded: true,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'pronghorn-wyoming',
    title: 'Pronghorn Antelope Hunt',
    outfitterName: 'Plains & Peaks Outfitters',
    species: 'Pronghorn Antelope',
    state: 'Wyoming',
    pricePerPerson: 1500,
    rating: 4.8,
    reviewCount: 41,
    weaponTypes: ['Rifle'],
    lodgingIncluded: false,
    guideType: 'semi_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'wild-boar-texas',
    title: 'Wild Boar Night Hunt',
    outfitterName: 'Lone Star Outfitters',
    species: 'Wild Boar',
    state: 'Texas',
    pricePerPerson: 600,
    rating: 4.5,
    reviewCount: 88,
    weaponTypes: ['Rifle', 'Bow'],
    lodgingIncluded: true,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'moose-alaska',
    title: 'Remote Alaska Moose Hunt',
    outfitterName: 'Alaska Wilderness Guides',
    species: 'Moose',
    state: 'Alaska',
    pricePerPerson: 7500,
    rating: 4.9,
    reviewCount: 22,
    weaponTypes: ['Rifle', 'Bow'],
    lodgingIncluded: true,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'turkey-kansas',
    title: 'Spring Turkey Hunt',
    outfitterName: 'Flint Hills Outfitters',
    species: 'Turkey',
    state: 'Kansas',
    pricePerPerson: 450,
    rating: 4.7,
    reviewCount: 53,
    weaponTypes: ['Shotgun', 'Bow'],
    lodgingIncluded: false,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'bighorn-new-mexico',
    title: 'Desert Bighorn Sheep Hunt',
    outfitterName: 'Southwest Trophy Hunts',
    species: 'Bighorn Sheep',
    state: 'New Mexico',
    pricePerPerson: 12000,
    rating: 5.0,
    reviewCount: 11,
    weaponTypes: ['Rifle'],
    lodgingIncluded: true,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'coues-deer-arizona',
    title: 'Coues Deer Rut Hunt',
    outfitterName: 'Arizona Backcountry Outfitters',
    species: 'Coues Deer',
    state: 'Arizona',
    pricePerPerson: 2800,
    rating: 4.8,
    reviewCount: 34,
    weaponTypes: ['Rifle', 'Bow'],
    lodgingIncluded: false,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'whitetail-kansas',
    title: 'Kansas Whitetail Rifle Hunt',
    outfitterName: 'Prairie State Hunts',
    species: 'Whitetail Deer',
    state: 'Kansas',
    pricePerPerson: 2200,
    rating: 4.6,
    reviewCount: 72,
    weaponTypes: ['Rifle'],
    lodgingIncluded: true,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
  {
    id: 'bison-montana',
    title: 'American Bison Hunt',
    outfitterName: 'Yellowstone Outfitters',
    species: 'Bison',
    state: 'Montana',
    pricePerPerson: 5500,
    rating: 4.7,
    reviewCount: 18,
    weaponTypes: ['Rifle', 'Bow', 'Muzzleloader'],
    lodgingIncluded: true,
    guideType: 'fully_guided',
    priceType: 'per_person',
    isExample: true,
  },
]

export const mockOutfitters: OutfitterCardProps[] = [
  {
    id: 'heartland-trophy',
    name: 'Heartland Trophy Outfitters',
    state: 'Missouri',
    species: ['Whitetail Deer', 'Turkey', 'Wild Boar'],
    totalListings: 6,
    rating: 4.9,
    reviewCount: 124,
    yearsInBusiness: 18,
    verified: true,
    isExample: true,
  },
  {
    id: 'rockies-wilderness',
    name: 'Rockies Wilderness Outfitters',
    state: 'Colorado',
    species: ['Elk', 'Mule Deer', 'Black Bear', 'Mountain Lion'],
    totalListings: 9,
    rating: 4.8,
    reviewCount: 203,
    yearsInBusiness: 24,
    verified: true,
    isExample: true,
  },
  {
    id: 'wind-river',
    name: 'Wind River Outfitters',
    state: 'Wyoming',
    species: ['Mule Deer', 'Elk', 'Pronghorn Antelope'],
    totalListings: 5,
    rating: 4.7,
    reviewCount: 87,
    yearsInBusiness: 12,
    verified: true,
    isExample: true,
  },
  {
    id: 'big-sky-adventures',
    name: 'Big Sky Hunting Adventures',
    state: 'Montana',
    species: ['Black Bear', 'Elk', 'Mule Deer', 'Bison'],
    totalListings: 8,
    rating: 4.6,
    reviewCount: 156,
    yearsInBusiness: 20,
    verified: false,
    isExample: true,
  },
  {
    id: 'lone-star-outfitters',
    name: 'Lone Star Outfitters',
    state: 'Texas',
    species: ['Wild Boar', 'Whitetail Deer', 'Nilgai', 'Axis Deer'],
    totalListings: 12,
    rating: 4.5,
    reviewCount: 311,
    yearsInBusiness: 15,
    verified: true,
    isExample: true,
  },
  {
    id: 'alaska-wilderness',
    name: 'Alaska Wilderness Guides',
    state: 'Alaska',
    species: ['Moose', 'Brown Bear', 'Caribou', 'Dall Sheep'],
    totalListings: 7,
    rating: 4.9,
    reviewCount: 98,
    yearsInBusiness: 30,
    verified: true,
    isExample: true,
  },
  {
    id: 'southwest-trophy',
    name: 'Southwest Trophy Hunts',
    state: 'New Mexico',
    species: ['Bighorn Sheep', 'Elk', 'Mule Deer', 'Pronghorn Antelope'],
    totalListings: 4,
    rating: 4.8,
    reviewCount: 61,
    yearsInBusiness: 9,
    verified: true,
    isExample: true,
  },
  {
    id: 'flint-hills-outfitters',
    name: 'Flint Hills Outfitters',
    state: 'Kansas',
    species: ['Turkey', 'Whitetail Deer', 'Wild Boar'],
    totalListings: 5,
    rating: 4.7,
    reviewCount: 145,
    yearsInBusiness: 11,
    verified: false,
    isExample: true,
  },
]
